syntax = "proto3";

package transaction;

service TransactionService {
  rpc CreateTransaction (CreateTransactionRequest) returns (CreateTransactionResponse);
  rpc GetTransaction (GetTransactionRequest) returns (GetTransactionResponse);
  rpc SearchTransactions (SearchTransactionsRequest) returns (SearchTransactionsResponse);
}

message CreateTransactionRequest {
  string title = 1;
  string description = 2;
  string property_address = 3;
  double price = 4;
  string buyer_id = 5;
  string seller_id = 6;
}

message CreateTransactionResponse {
  string transaction_id = 1;
  string state = 2;
}

message GetTransactionRequest {
  string transaction_id = 1;
}

message GetTransactionResponse {
  string transaction_id = 1;
  string title = 2;
  string description = 3;
  string property_address = 4;
  double price = 5;
  string buyer_id = 6;
  string seller_id = 7;
  string state = 8;
}

message SearchTransactionsRequest {
  string query = 1;
}

message SearchTransactionsResponse {
  repeated GetTransactionResponse items = 1;
}
